# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a38b55d02c63f908e5854b5a8b69098ade47e665a3a810a56f9a1bf4cc98909f81cc57ff63d067a514755953cdc12bcf2384e81da6218df45e63e61c08a9f03

test:
  secret_key_base: cdfb3e4c9ee6b269b7d0a2b609e5a6f37a6d7ceca559cefb6cd9d282bfed43531541f98f45f7d235d2217fd37727ee2d045ee041064f1f9d1f7a4558a765fad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
